"""Emit frontend/src/lib/mcp-template-catalog/catalog.generated.ts from structured data."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "src" / "lib" / "mcp-template-catalog" / "catalog.generated.ts"
JSON_OUT = ROOT / "backend" / "app" / "data" / "mcp_template_catalog.json"


def entry(
    eid: str,
    tier: str,
    name: str,
    tagline: str,
    category: str,
    runtime: str,
    transport: str,
    overview: str,
    design: str,
    tools: list[str],
    extensions: str,
    risks: str,
) -> dict:
    return {
        "id": eid,
        "tier": tier,
        "name": name,
        "tagline": tagline,
        "category": category,
        "primaryRuntime": runtime,
        "transport": transport,
        "overview": overview,
        "design": design,
        "suggestedTools": tools,
        "extensionIdeas": extensions,
        "risks": risks,
    }


BASIC: list[dict] = [
    entry(
        "basic-echo-json",
        "basic",
        "Echo and ping",
        "Teach MCP request/response with a trivial JSON echo tool.",
        "learning",
        "typescript",
        "stdio",
        "Ideal first server: the model calls a single tool with arbitrary JSON and receives the same payload wrapped with server metadata.",
        "Expose one `echo` tool whose input schema is a generic object plus optional string `label`. Handler returns `{ receivedAt, label, payload }`. Add `ping` returning `{ ok: true, version }` for health checks. Keep transport stdio only. Validate maximum JSON depth/size in handler before echo to avoid abuse. Log only aggregate counts, not payloads, in production.",
        ["echo", "ping"],
        "Add optional JSON Schema validation against a user-supplied schema resource.",
        "Echoing secrets from prompts can leak into logs if logging is misconfigured.",
    ),
    entry(
        "basic-math-sandbox",
        "basic",
        "Safe math evaluator",
        "Evaluate arithmetic expressions without `eval`.",
        "utilities",
        "python",
        "stdio",
        "Agents frequently need deterministic calculations for pricing, sizing, or scoring without hallucinating numbers.",
        "Use `ast` parsing in Python to allow only numeric literals and operators (+ - * / **, parentheses). Reject names, attribute access, imports. Return both float and rational string for precision-sensitive cases. Surface parse errors as structured tool errors. Optional second tool `convert_units` with a static conversion table.",
        ["evaluate_expression", "convert_units"],
        "Wire a tiny test matrix of golden expressions in project test cases.",
        "Never fall back to `eval`; whitelist grammar only.",
    ),
    entry(
        "basic-id-and-tokens",
        "basic",
        "UUID and token helpers",
        "Generate UUIDv4, nanoid-style strings, and random bytes (hex).",
        "security-basics",
        "typescript",
        "stdio",
        "Useful for correlating runs, creating draft resource IDs, or populating forms in automation flows.",
        "Tools: `uuid_v4`, `random_hex` with `bytes` capped (e.g. max 64), `slug_from_title` with unicode normalization. All generation uses crypto RNG. Return counts when batching (`n` parameter with hard cap). Document entropy guarantees in tool descriptions.",
        ["uuid_v4", "random_hex", "slug_from_title"],
        "Add optional base32 Crockford encoding for human-readable IDs.",
        "Rate-limit batch generation if exposed publicly.",
    ),
    entry(
        "basic-codec-suite",
        "basic",
        "Base64 and hex codecs",
        "Encode/decode text and small binary blobs safely.",
        "utilities",
        "python",
        "stdio",
        "Agents working with APIs, webhooks, or embedded payloads often need reversible encodings without leaving the MCP host.",
        "Provide `base64_encode`, `base64_decode`, `hex_encode`, `hex_decode` with max input length enforcement. Decode failures return typed errors. Never write to disk; memory-only. Optionally add `crc32` for quick integrity checks on text.",
        ["base64_encode", "base64_decode", "hex_encode", "hex_decode"],
        "Add gzip+base64 helper for compress-then-encode with size ceiling.",
        "Decoding untrusted base64 can allocate large buffers—enforce strict size caps.",
    ),
    entry(
        "basic-json-tools",
        "basic",
        "JSON lint, format, validate",
        "Pretty-print JSON and validate against a JSON Schema.",
        "data",
        "typescript",
        "stdio",
        "Designers often paste malformed JSON from logs; this MCP normalizes and validates before codegen or storage.",
        "Tools: `format_json` (indent option), `minify_json`, `validate_json_schema` taking `instance` and `schema` objects. Use a vetted validator library with `unsafe` modes disabled. Return pointer-style error paths for schema failures to help the model fix documents.",
        ["format_json", "minify_json", "validate_json_schema"],
        "Add `json_merge_patch` for RFC7396 style merges with conflict reporting.",
        "Large JSON can OOM—enforce byte limits per request.",
    ),
    entry(
        "basic-time-and-tz",
        "basic",
        "Timestamp and timezone utilities",
        "Convert between Unix epoch, ISO-8601, and named time zones.",
        "utilities",
        "python",
        "stdio",
        "Scheduling, log correlation, and incident timelines need reliable time conversions without external APIs.",
        "Tools: `parse_iso`, `to_epoch`, `from_epoch`, `shift_tz` using zoneinfo/tzdata. Reject ambiguous local times explicitly. Return canonical ISO with offset. Include `now_utc` for deterministic tests with injectable clock in unit tests (design note only).",
        ["parse_iso", "to_epoch", "from_epoch", "shift_tz", "now_utc"],
        "Add business-day add/subtract with a static holiday list parameter.",
        "DST edge cases must be documented in tool descriptions to avoid silent shifts.",
    ),
    entry(
        "basic-url-parse",
        "basic",
        "URL builder and normalizer",
        "Parse URLs, merge query params, and validate schemes.",
        "web",
        "typescript",
        "stdio",
        "Constructing signed webhook URLs or deep links is error-prone for LLMs; structured URL tools reduce mistakes.",
        "Implement `parse_url` returning components, `merge_query` with sorted keys for stable output, `strip_credentials` for logging-safe views. Allowlist schemes (http, https, file optional). Reject javascript: and data: schemes outright.",
        ["parse_url", "merge_query", "strip_credentials"],
        "Add `to_punycode` / `from_punycode` for internationalized domains.",
        "Never auto-fetch URLs in basic tier—keep network out of scope.",
    ),
    entry(
        "basic-markdown-frontmatter",
        "basic",
        "Markdown front-matter extractor",
        "Split YAML/TOML front matter from markdown body for docs pipelines.",
        "content",
        "python",
        "stdio",
        "Documentation agents need structured metadata (title, tags) separate from prose bodies.",
        "Tool `split_frontmatter` reads a markdown string, detects delimiter `---`, parses YAML with safe loader (no arbitrary objects), returns `{ meta, body }`. Second tool `strip_code_fences` optionally removes fenced blocks for summarization. Cap input size.",
        ["split_frontmatter", "strip_code_fences"],
        "Support TOML front matter via a bounded parser.",
        "YAML anchors can be abused—disable them in loader settings.",
    ),
    entry(
        "basic-text-stats",
        "basic",
        "Text statistics",
        "Word counts, reading time estimates, and simple readability hints.",
        "nlp-lite",
        "typescript",
        "stdio",
        "Content workflows need quick metrics without shipping full NLP models.",
        "Tools: `word_count` with unicode word boundaries, `sentence_count`, `estimate_reading_time` using configurable WPM, `ngram_preview` for top bigrams (local only). No external calls. Return histogram optional for character classes.",
        ["word_count", "sentence_count", "estimate_reading_time", "ngram_preview"],
        "Add language-agnostic syllable proxy for rough grade level.",
        "Do not claim clinical readability scores—keep disclaimers in descriptions.",
    ),
    entry(
        "basic-fake-deterministic",
        "basic",
        "Deterministic fake records",
        "Generate reproducible placeholder rows for UI mocks and tests.",
        "testing",
        "typescript",
        "stdio",
        "Product teams need GDPR-safe synthetic rows keyed by a seed for reproducible screenshots.",
        "Tool `fake_records` accepts `seed`, `count`, `shape` describing fields (string/email/int/enum). Use a portable PRNG (mulberry32) to derive values. No real PII patterns (avoid real TLDs if possible). Export JSON rows only.",
        ["fake_records"],
        "Mirror CSV output as second tool with RFC4180 quoting.",
        "Clearly label output as synthetic in the tool response text.",
    ),
    entry(
        "basic-color-convert",
        "basic",
        "Color conversions",
        "Convert HEX ↔ RGB ↔ HSL and compute contrast ratios.",
        "design",
        "python",
        "stdio",
        "UI iteration chats need accessible contrast checks quickly.",
        "Tools: `hex_to_rgb`, `rgb_to_hex`, `relative_luminance`, `contrast_ratio` following WCAG. Clamp channels, validate ranges. Return both float and rounded ratios. Document formula version in description.",
        ["hex_to_rgb", "rgb_to_hex", "relative_luminance", "contrast_ratio"],
        "Add named palette suggestions from a static safe palette table.",
        "Do not claim calibrated color accuracy for HDR colorspaces.",
    ),
    entry(
        "basic-regex-smoke",
        "basic",
        "Bounded regex tester",
        "Run a regex against haystack with step limits and timeouts.",
        "utilities",
        "typescript",
        "stdio",
        "Debugging log parsers is common; this keeps regex execution bounded in-process.",
        "Use engine with linear-time mode or RE2 if available; otherwise enforce max steps / max matches / timeout. Tools: `regex_test` returning match spans, `regex_replace` with replace limit. Reject catastrophic patterns via pre-scan heuristics where possible.",
        ["regex_test", "regex_replace"],
        "Expose named capture group extraction as structured JSON.",
        "Catastrophic backtracking risk—document limits prominently.",
    ),
    entry(
        "basic-csv-peek",
        "basic",
        "CSV shape inspector",
        "Infer delimiter, headers, and preview rows without full parse of huge files.",
        "data",
        "python",
        "stdio",
        "Agents analyzing tabular uploads need schema guesses before SQL load.",
        "Accept CSV string (not path) capped by bytes. Tools: `sniff_dialect`, `preview_rows`, `validate_rectangular`. Use csv module with sane limits on field size. Return inferred types per column as heuristic strings only.",
        ["sniff_dialect", "preview_rows", "validate_rectangular"],
        "Add `hash_columns` to fingerprint column names for drift detection.",
        "Do not execute formulas starting with = in cells—strip or escape.",
    ),
    entry(
        "basic-slugify",
        "basic",
        "Slug and filename sanitizer",
        "Produce URL-safe slugs and Windows/macOS safe filenames.",
        "filesystem-lite",
        "typescript",
        "stdio",
        "Downstream build scripts need stable artifact names from human titles.",
        "Tools: `slugify_unicode`, `truncate_middle`, `ensure_extension`. Normalize NFKC, replace disallowed chars, collapse dashes. Reserved Windows device names blocked. Max length enforced.",
        ["slugify_unicode", "truncate_middle", "ensure_extension"],
        "Add collision avoidance suffix `_2`, `_3` based on optional counter param.",
        "Never accept absolute paths—strings only.",
    ),
    entry(
        "basic-hash-text",
        "basic",
        "Text hashing",
        "SHA-256 / SHA-384 digests of UTF-8 strings for cache keys.",
        "security-basics",
        "python",
        "stdio",
        "Deduplication and cache addressing often need deterministic hashes without shipping files.",
        "Tools: `sha256_hex`, `sha384_hex` with optional `salt` parameter mixed via HMAC pattern. Never hash secrets provided by user without warning in description. Constant-time compare helper optional for MAC tags.",
        ["sha256_hex", "sha384_hex"],
        "Add BLAKE2b as optional fast non-password hashing.",
        "Discourage password hashing in descriptions—wrong tool for that.",
    ),
    entry(
        "basic-yaml-json",
        "basic",
        "YAML ↔ JSON conversion",
        "Parse YAML to JSON and stringify JSON to YAML with safe options.",
        "data",
        "python",
        "stdio",
        "Config agents juggling Kubernetes manifests need conversions without kubectl.",
        "Use safe_load equivalents, disable arbitrary Python types, depth limits. Tools: `yaml_to_json`, `json_to_yaml`. Report line/column on parse errors.",
        ["yaml_to_json", "json_to_yaml"],
        "Add `strip_comments` preserving structure where possible.",
        "YAML can execute types in unsafe loaders—keep loader strict.",
    ),
    entry(
        "basic-pii-mask",
        "basic",
        "PII masking for logs",
        "Redact emails, phone patterns, and credit card-like sequences in text blobs.",
        "privacy",
        "typescript",
        "stdio",
        "Before sending logs/snippets to an LLM vendor, operators want quick masking.",
        "Tools: `mask_emails`, `mask_phones`, `mask_cards` using regex with Luhn check for cards. Return mapping table optional (off by default) to avoid leaking originals side channel. Cap input size.",
        ["mask_emails", "mask_phones", "mask_cards"],
        "Add configurable allowlist domains for support emails.",
        "Masking is heuristic—not legal compliance alone.",
    ),
    entry(
        "basic-phone-normalize",
        "basic",
        "Phone number normalization",
        "Parse to E.164 using libphonenumber metadata subset or full lib if bundled.",
        "utilities",
        "python",
        "stdio",
        "CRM prompts need canonical phone formats for dedupe keys.",
        "Tool `normalize_phone` with `default_region` parameter. Return `e164`, `valid`, `type` (mobile/fixed line unknown). Invalid inputs return structured errors, not exceptions text.",
        ["normalize_phone", "format_national"],
        "Add `compare_loose` for fuzzy dedupe suggestions.",
        "Metadata updates require dependency bump discipline.",
    ),
    entry(
        "basic-http-status-catalog",
        "basic",
        "HTTP status reference",
        "Lookup meaning, retryability, and caching implications of status codes.",
        "web",
        "typescript",
        "stdio",
        "Junior agents debugging API failures benefit from structured guidance baked into tools.",
        "Static table keyed by code returning `{ name, retryable, idempotent_retry, cacheable }`. Tool `explain_status` and `suggest_backoff` with exponential table (no network).",
        ["explain_status", "suggest_backoff"],
        "Link to MDN anchors in description strings for human follow-up.",
        "Informational only—not a substitute for server-specific semantics.",
    ),
    entry(
        "basic-stack-trace-parse",
        "basic",
        "Stack trace frame parser",
        "Extract `{ file, line, fn }` frames from common JVM/Node/Python traces.",
        "devtools",
        "python",
        "stdio",
        "Support engineers paste traces into chat; structured frames help triage.",
        "Tool `parse_stack` with `flavor` enum. Return ordered frames, detect innermost application frames heuristically. Never execute code. Second tool `collapse_duplicates` for repeated frames.",
        ["parse_stack", "collapse_duplicates"],
        "Add Go/Rust regex flavors as additional parsers.",
        "Paths may contain sensitive directory names—warn in tool doc.",
    ),
    entry(
        "basic-jwt-decode-inspect",
        "basic",
        "JWT inspector (decode only)",
        "Decode JWT header/payload without verification for debugging.",
        "security-basics",
        "typescript",
        "stdio",
        "Developers need to read `aud`, `exp`, `kid` quickly when fixing auth issues.",
        "Tool `decode_jwt` splits segments, base64url-decodes JSON, validates JSON shape. **No** signature verification tool included—description states trust implications. Reject `none` alg with explicit error.",
        ["decode_jwt"],
        "Pair with separate verified flow in intermediate tier.",
        "Misuse can encourage trusting unverified tokens—emphasize risk text.",
    ),
    entry(
        "basic-text-diff",
        "basic",
        "Unified diff for strings",
        "Produce unified diff hunks between two text blobs for code review assistance.",
        "devtools",
        "python",
        "stdio",
        "Agents summarizing PR impact need a compact diff without shelling to git.",
        "Use Myers diff with max hunk size and line count caps. Tool `unified_diff` with context lines parameter. Optional `word_diff` for prose. Return patch text only.",
        ["unified_diff", "word_diff"],
        "Add `diff_stats` for additions/deletions counts.",
        "Large texts are CPU heavy—enforce caps.",
    ),
    entry(
        "basic-ip-validation",
        "basic",
        "IP address validation",
        "Validate IPv4/IPv6, CIDR membership checks without DNS.",
        "network-lite",
        "typescript",
        "stdio",
        "Access-control drafting in chat benefits from boolean checks on literals.",
        "Tools: `parse_ipv4`, `parse_ipv6`, `cidr_contains`. Use bigint or JS libraries for IPv6 math carefully. Return normalized compressed IPv6 string.",
        ["parse_ipv4", "parse_ipv6", "cidr_contains"],
        "Add `summarize_cidr` for host count (bounded ranges only).",
        "No reverse DNS—avoid data exfil vectors.",
    ),
    entry(
        "basic-mime-from-ext",
        "basic",
        "MIME type from extension",
        "Map filename extensions to IANA-like MIME types using a static table.",
        "web",
        "typescript",
        "stdio",
        "Upload pipelines need quick content-type guesses before sniffing bytes.",
        "Static JSON map loaded at startup. Tools: `guess_mime`, `list_exts_for_mime` reverse lookup. Unknown returns `application/octet-stream`.",
        ["guess_mime", "list_exts_for_mime"],
        "Allow vendor subtree `x-` overrides via config object in MCP config.",
        "Sniffing bytes is more accurate—document limitation.",
    ),
    entry(
        "basic-cron-humanize",
        "basic",
        "Cron expression explainer",
        "Parse standard 5-field cron into human-readable constraints.",
        "ops-lite",
        "python",
        "stdio",
        "SRE chats translating scheduler snippets need safe offline parsing.",
        "Tool `explain_cron` supporting common macros (`@hourly`). Validate ranges. Optional `next_n_runs` with bounded simulation using UTC clock. Cap N.",
        ["explain_cron", "next_n_runs"],
        "Support Quartz 6-field as optional mode with explicit flag.",
        "DST issues for local tz—prefer UTC in docs.",
    ),
    entry(
        "basic-branch-name",
        "basic",
        "Git branch name sanitizer",
        "Turn arbitrary titles into valid, unique-ish branch names.",
        "devtools",
        "typescript",
        "stdio",
        "Issue titles become branch names in many flows; sanitization prevents git errors.",
        "Lowercase, replace spaces with `-`, strip punctuation except `/` disallow, max length 60. Tool `sanitize_branch` and `is_valid_ref` for education.",
        ["sanitize_branch", "is_valid_ref"],
        "Add conventional commit scope sanitizer sibling tool.",
        "Does not check remote collisions.",
    ),
]

INTERMEDIATE: list[dict] = [
    entry(
        "int-http-json-client",
        "intermediate",
        "Authenticated JSON HTTP client",
        "GET/POST JSON with bearer token sourced from env, timeouts, and redacted logs.",
        "integration",
        "typescript",
        "stdio",
        "Most internal tools wrap REST services; this template encodes safe defaults for AI-driven automation.",
        "Single `request` tool taking `method`, `url`, `headers`, `jsonBody`, `timeoutMs`. Pull bearer from `process.env.MCP_HTTP_TOKEN`. Enforce allowlist hostnames via config in MCP server metadata. Cap response bytes; truncate with hash of full body id. Structured errors for HTTP status and network codes.",
        ["http_json_request"],
        "Add retry with jitter only for idempotent methods.",
        "SSRF risk—hostname allowlist mandatory; never pass raw user URL without validation layer.",
    ),
    entry(
        "int-paginated-fetch",
        "intermediate",
        "Cursor-based pagination fetcher",
        "Follow `next` links or opaque cursors until budget or terminal.",
        "integration",
        "python",
        "stdio",
        "Listing large collections (issues, orders) needs disciplined pagination to avoid runaway token usage.",
        "Tool `fetch_all_pages` accepts `first_url`, `max_pages`, `max_records`, `cursor_json_path`. Uses httpx async with timeouts. Stops on 4xx except 429 with bounded retries respecting `Retry-After`. Accumulate items client-side with streaming discard to cap memory.",
        ["fetch_all_pages"],
        "Add `estimate_total` if API exposes total count header.",
        "Respect robots/terms of target API—document user responsibility.",
    ),
    entry(
        "int-webhook-signature",
        "intermediate",
        "Webhook HMAC verifier",
        "Verify GitHub/Stripe-like signatures with constant-time compare.",
        "security",
        "typescript",
        "stdio",
        "Inbound hook testing in dev environments often lacks a full framework.",
        "Tools: `verify_hmac_sha256` with `secret`, `payload`, `signature_hex`, optional `prefix` like `sha256=`. Use timing-safe compare. Second tool `parse_github_signature_headers` for convenience. Never log secrets.",
        ["verify_hmac_sha256", "parse_github_signature_headers"],
        "Add Ed25519 verify variant for modern providers.",
        "Rotating secrets requires dual-secret window—document pattern only here.",
    ),
    entry(
        "int-jira-readonly",
        "intermediate",
        "Jira issue reader",
        "Fetch issue JSON and comments with PAT from env.",
        "integration",
        "python",
        "stdio",
        "Support triage bots need structured fields without write risk.",
        "Tools: `get_issue`, `list_comments` using Jira REST v3. Base URL and email+token auth from env. Strip HTML bodies to markdown-lite via simple tag strip (bounded). Cache etag optional in-memory with TTL.",
        ["get_issue", "list_comments"],
        "Add JQL search with `maxResults` cap.",
        "PAT scopes must be read-only; warn about HTML injection in fields.",
    ),
    entry(
        "int-slack-post",
        "intermediate",
        "Slack message poster",
        "Post to a channel with blocks JSON using bot token.",
        "integration",
        "typescript",
        "stdio",
        "Operational MCPs often notify channels when pipelines complete or need approval.",
        "Tool `post_message` with `channel`, `text`, optional `blocks`. Use chat.postMessage API. Validate `blocks` size. Map API errors to structured tool errors. Optional `lookup_user` by email with scoped token.",
        ["post_message", "lookup_user"],
        "Add thread reply tool with `thread_ts`.",
        "Token leakage through prompts—prefer env and never echo token back.",
    ),
    entry(
        "int-github-gist-read",
        "intermediate",
        "GitHub gist reader",
        "Fetch public or authenticated gists as text for sharing repro snippets.",
        "integration",
        "python",
        "stdio",
        "Education flows pull starter code from gists without cloning repos.",
        "Tools: `get_gist`, `list_gist_files` using token if present. Return filenames and truncated contents with `max_chars` per file. Respect rate limits with backoff.",
        ["get_gist", "list_gist_files"],
        "Add `search_gists` for user's own gists only.",
        "Private gist exposure—ensure auth scope minimal.",
    ),
    entry(
        "int-openapi-summarize",
        "intermediate",
        "OpenAPI operation catalog",
        "Parse OpenAPI 3 JSON/YAML string and list operations grouped by tag.",
        "api-design",
        "typescript",
        "stdio",
        "Before codegen, agents need a compact map of paths and security requirements.",
        "Tool `list_operations` returning `{ method, path, operationId, tags, security }`. Cap operations count; warn on huge specs. Second tool `get_operation` for single operation schema subset.",
        ["list_operations", "get_operation"],
        "Add `diff_operations` between two spec strings for migration notes.",
        "Specs may be untrusted YAML—use safe parser settings.",
    ),
    entry(
        "int-s3-presign-pattern",
        "intermediate",
        "S3 presigned URL pattern",
        "Design tools that mint GET/PUT URLs using SDK with session creds from env.",
        "cloud",
        "python",
        "stdio",
        "Artifact handoff between agents and humans often uses short-lived URLs instead of streaming bytes through the model.",
        "Tools: `presign_put`, `presign_get` with bucket allowlist, key prefix allowlist, TTL cap. Validate key does not contain `..` segments. Return URL + expiry epoch only.",
        ["presign_put", "presign_get"],
        "Add multipart initiate/complete as separate advanced server.",
        "Misconfigured bucket policies can expose data—pair with IAM guidance.",
    ),
    entry(
        "int-redis-kv",
        "intermediate",
        "Redis string GET/SET with TTL",
        "Simple KV cache tools against Redis URL in env.",
        "data",
        "typescript",
        "stdio",
        "Session-scoped memoization for multi-step agent workflows reduces duplicate API calls.",
        "Use ioredis with TLS URL support. Tools: `cache_get`, `cache_set` with `ttlSeconds` max cap, `cache_delete`. Namespace keys with `mcp:{tenant}:` from config. Never accept arbitrary connection string from tool args.",
        ["cache_get", "cache_set", "cache_delete"],
        "Add `incr` with TTL refresh for rate counters.",
        "Redis command injection not applicable but key cardinality can explode—enforce key length and count quotas.",
    ),
    entry(
        "int-postgres-readonly",
        "intermediate",
        "PostgreSQL read replica queries",
        "Parameterized SELECT-only guard with statement timeout.",
        "database",
        "python",
        "stdio",
        "Analytics assistants need SQL access without mutation risk.",
        "Tool `select` taking `sql` and `params`. Reject multi-statement and non-SELECT via SQL parser or aggressive regex + EXPLAIN guard. Set `default_transaction_read_only=on` and `statement_timeout`. Row cap and byte cap on results.",
        ["select", "explain_plan"],
        "Add `list_tables` using `information_schema` with allowlist schema.",
        "SQL injection if parameterization bypassed—validate strictly.",
    ),
    entry(
        "int-notion-fetch",
        "intermediate",
        "Notion page exporter",
        "Fetch page blocks and flatten to text/markdown-like structure.",
        "integration",
        "typescript",
        "stdio",
        "Research agents aggregate specs scattered in Notion.",
        "Tool `get_page_markdown` using Notion API with integration token env. Recursively fetch blocks with depth cap. Toggle toggles respected. Rate limit aware batching.",
        ["get_page_markdown", "search_pages"],
        "Add database row query tool with column allowlist.",
        "Notion content may contain secrets—apply org DLP policies upstream.",
    ),
    entry(
        "int-linear-issues",
        "intermediate",
        "Linear GraphQL issue search",
        "Search issues by team, state, and label with cost limits.",
        "integration",
        "python",
        "stdio",
        "Engineering copilots need ticket context with less noise than full web UI.",
        "Single `graphql` tool discouraged—instead curated `search_issues` building a parameterized query. API key from env. Return slim issue objects. Cap nodes.",
        ["search_issues", "get_issue"],
        "Add `post_comment` guarded behind feature flag config.",
        "GraphQL complexity can spike costs—keep queries minimal.",
    ),
    entry(
        "int-google-calendar-freebusy",
        "intermediate",
        "Calendar free/busy reader",
        "Query freebusy ranges for scheduling assistants.",
        "integration",
        "typescript",
        "stdio",
        "Meeting negotiation flows need busy blocks without exposing event titles if policy requires.",
        "OAuth access token from env refresh handled externally. Tool `freebusy` takes calendar ids list, timeMin/timeMax RFC3339. Returns busy arrays only. Optional `timezone` normalization.",
        ["freebusy"],
        "Add working hours intersection helper tool.",
        "OAuth scopes must be least privilege; tokens are secrets.",
    ),
    entry(
        "int-sendgrid-template-mail",
        "intermediate",
        "SendGrid templated email",
        "Send mail using dynamic template ID and data JSON.",
        "integration",
        "python",
        "stdio",
        "Transactional notifications triggered by agent-observed events (with human approval patterns).",
        "Tool `send_template_email` with `to`, `template_id`, `dynamic_data`. API key env. Sandbox mode flag routes to sink address allowlist. Dry-run tool returns rendered size estimate without send.",
        ["send_template_email", "dry_run_template"],
        "Add attachment stub rejecting attachments for safety by default.",
        "Email abuse potential—rate limit and capture audit id from provider response.",
    ),
    entry(
        "int-twilio-sms",
        "intermediate",
        "Twilio SMS notifier",
        "Send SMS to allowlisted E.164 numbers only.",
        "integration",
        "typescript",
        "stdio",
        "Paging on-call engineers from automated health checks.",
        "Tools: `send_sms` requiring `to` in allowlist config file path or embedded static list for demo. `status_lookup` for message SID. Credentials via env. Hard cap messages per day stored in Redis optional.",
        ["send_sms", "status_lookup"],
        "Add voice call initiation as separate high-risk server.",
        "SMS fraud and cost overruns—strict allowlist and quotas.",
    ),
    entry(
        "int-stripe-customer",
        "intermediate",
        "Stripe customer lookup",
        "Retrieve customer and subscriptions read-only.",
        "integration",
        "python",
        "stdio",
        "Support agents with scoped access need billing context without dashboard clicks.",
        "Secret key in env with restricted Stripe key. Tools: `get_customer`, `list_subscriptions`. Never return full card numbers; rely on Stripe objects. Log request ids only.",
        ["get_customer", "list_subscriptions", "list_invoices"],
        "Add `search_customers` by email hash if privacy tightened.",
        "PCI scope minimization—prefer dashboard links for sensitive actions.",
    ),
    entry(
        "int-hubspot-contact",
        "intermediate",
        "HubSpot CRM contact fetch",
        "Search contacts by email and return non-sensitive fields.",
        "integration",
        "typescript",
        "stdio",
        "Sales assistants need lifecycle stage and owner without exporting entire CRM.",
        "Private app token env. Tools: `find_contact_by_email`, `get_contact`. Field allowlist in server config to strip PII not needed. Rate limit wrapper.",
        ["find_contact_by_email", "get_contact"],
        "Add `log_engagement` write tool behind RBAC config.",
        "CRM data residency and consent—document enterprise policy hooks.",
    ),
    entry(
        "int-airtable-read",
        "intermediate",
        "Airtable base read",
        "List records with view and filter formula capped.",
        "integration",
        "python",
        "stdio",
        "Lightweight ops trackers often live in Airtable; agents read status boards.",
        "Tool `list_records` with `baseId`, `tableIdOrName`, `view`, `maxRecords`, `fields` allowlist. PAT in env. Validate formula length. Paginate offset loop with cap.",
        ["list_records", "get_record"],
        "Add `meta_bases` discovery tool.",
        "Formula injection less risky read-side but still validate syntax length.",
    ),
    entry(
        "int-es-query-helper",
        "intermediate",
        "Elasticsearch query DSL builder",
        "Compose bool queries from structured constraints safely.",
        "data",
        "typescript",
        "stdio",
        "Observability copilots translate questions into DSL without pasting huge JSON by hand each time.",
        "Tools: `build_bool_query` from `must`, `filter`, `should` clause objects with whitelisted field names. `run_search` optional if ES URL in env with read-only role. Size caps.",
        ["build_bool_query", "run_search"],
        "Add `kql_to_query` experimental translator with disclaimer.",
        "Query cost explosions—enforce size and timeout.",
    ),
    entry(
        "int-docker-stats",
        "intermediate",
        "Docker container stats reader",
        "Read `docker stats --no-stream` JSON via local socket (pattern).",
        "ops",
        "python",
        "stdio",
        "Local dev agents diagnose resource hogs on engineer laptops with structured numbers.",
        "Subprocess to `docker` CLI not ideal; prefer Docker SDK with unix socket, read-only. Tools: `list_running`, `inspect_stats`. Fail gracefully if daemon absent.",
        ["list_running", "inspect_stats"],
        "Add `prune_images` as blocked stub explaining risk.",
        "Exposes container names/env—sensitivity in shared hosts.",
    ),
    entry(
        "int-k8s-pod-list",
        "intermediate",
        "Kubernetes pod lister",
        "List pods in namespace with field selector using kubeconfig from env path.",
        "ops",
        "typescript",
        "stdio",
        "Incident bots fetch pod phases and restart counts for quick summaries.",
        "Use official client with kubeconfig file path from `KUBECONFIG` env (not args). Tools: `list_pods`, `get_pod_logs` with tail line cap. Read-only cluster role binding assumed.",
        ["list_pods", "get_pod_logs"],
        "Add `describe_events` for namespace events.",
        "Logs may contain secrets—apply redaction filters optional.",
    ),
    entry(
        "int-terraform-plan-parse",
        "intermediate",
        "Terraform JSON plan summarizer",
        "Parse `terraform show -json` output and summarize create/change/destroy counts.",
        "ops",
        "python",
        "stdio",
        "CI comments summarizing plans reduce noise in PR threads.",
        "Tool `summarize_plan` reading plan JSON string (not executing terraform). Extract resource changes grouped by module. Cap resources listed; overflow counter.",
        ["summarize_plan", "list_modules"],
        "Add `risk_flags` heuristics for destroy -create cycles.",
        "Plans may embed sensitive values if not redacted—warn operators.",
    ),
    entry(
        "int-prometheus-query",
        "intermediate",
        "Prometheus instant query",
        "Run PromQL instant queries against base URL with auth header.",
        "observability",
        "typescript",
        "stdio",
        "SRE copilots fetch metric values for anomaly explanations.",
        "Tool `query` with `query`, `time`. API URL and bearer from env. Enforce max range by rejecting range queries in this template (instant only). Response size cap.",
        ["query", "metadata_labels"],
        "Add `alerts` fetch from Alertmanager separate tool.",
        "PromQL can be expensive—server-side limits vary; enforce client timeouts.",
    ),
    entry(
        "int-grafana-dashboard-list",
        "intermediate",
        "Grafana dashboard search",
        "Search dashboards by tag and return uid/slug URLs.",
        "observability",
        "python",
        "stdio",
        "Navigate large Grafana installs by metadata instead of UI search.",
        "Service account token env. Tools: `search_dashboards`, `get_dashboard_json` with size cap and field stripping. Base URL from env.",
        ["search_dashboards", "get_dashboard_json"],
        "Add `list_datasources` read-only for type discovery.",
        "Dashboard JSON may include datasource UIDs tied to infra topology—sensitivity.",
    ),
    entry(
        "int-oauth-introspect",
        "intermediate",
        "OAuth2 token introspection client",
        "Call RFC7662 introspection endpoint with client credentials.",
        "security",
        "typescript",
        "stdio",
        "Agents acting on behalf of users need to confirm token active/scopes before side effects.",
        "Tool `introspect` taking `token`, returns `{ active, scope, client_id, exp }`. Client id/secret from env. POST form-encoded. Cache negative results briefly optional.",
        ["introspect"],
        "Add `parse_jwt_scopes_unverified` helper for debugging only.",
        "Introspection endpoints may log—coordinate with IdP owners.",
    ),
    entry(
        "int-graphql-github",
        "intermediate",
        "GitHub GraphQL search",
        "Search issues/PRs with cost-aware query templates.",
        "integration",
        "python",
        "stdio",
        "Developer experience bots mine GitHub without scraping HTML.",
        "Curated queries for `search` type ISSUE_PR with variables; cap `first`. PAT scopes documented. Map rateLimit cost field to throttle locally.",
        ["search_issues_prs", "get_pull_request_files"],
        "Add `request_reviewers` write tool gated off by default.",
        "Token scope creep risk—ship minimal PAT templates.",
    ),
    entry(
        "int-microsoft-graph-mail-read",
        "intermediate",
        "Microsoft Graph mail read",
        "List recent messages metadata only from shared mailbox.",
        "integration",
        "typescript",
        "stdio",
        "Executive assistants summaries without downloading full MIME bodies by default.",
        "OAuth token env. Tools: `list_messages` returning id/subject/from/receivedDateTime only. `get_message_body` with max chars. Optional sensitivity label id if tenant supports.",
        ["list_messages", "get_message_body"],
        "Add calendar events list variant reusing auth layer.",
        "Mailbox confidentiality—enterprise DLP mandatory.",
    ),
    entry(
        "int-cloudflare-dns-read",
        "intermediate",
        "Cloudflare DNS record reader",
        "List DNS records for zone id with token from env.",
        "integration",
        "python",
        "stdio",
        "Infra agents verify propagation or detect stale A records during cutovers.",
        "Tool `list_dns_records` with pagination and type filter. Zone id from config not freeform user string if possible. Token scoped to DNS read.",
        ["list_dns_records"],
        "Add `purge_cache` behind dangerous=false default config.",
        "DNS data reveals infra—treat as confidential.",
    ),
]

ADVANCED: list[dict] = [
    entry(
        "adv-multitenant-routing",
        "advanced",
        "Multi-tenant MCP router",
        "Route each tool call to tenant-specific backends using JWT tenant claim.",
        "platform",
        "typescript",
        "stdio",
        "Hosted MCP platforms must isolate customers while sharing one binary deployment.",
        "On `initialize`, read optional `tenantId` from auth claims injected by sidecar (design). Tool handlers first resolve `tenantContext` from validated JWT (signature verified upstream). Data plane calls include tenant id header. Separate connection pools per tenant in pool map with LRU cap. Audit log tool emits structured events to stdout for SIEM.",
        ["resolve_tenant", "tenant_health", "audit_event"],
        "Add per-tenant feature flag cache with TTL.",
        "Mis-issued tokens cross tenants—verify signing keys rotation and audience.",
    ),
    entry(
        "adv-rate-limit-aggregator",
        "advanced",
        "Rate-limited multi-API aggregator",
        "Combine several upstream JSON APIs with token bucket per host.",
        "integration",
        "python",
        "stdio",
        "Research agents hit many providers; uncapped concurrency gets blocked or expensive.",
        "Async httpx client with per-host buckets persisted in Redis optional. Tools: `fan_out_get` accepting list of URLs with shared schema allowlist. Partial results with per-host error objects. Circuit breaker after consecutive failures.",
        ["fan_out_get", "circuit_status"],
        "Add adaptive concurrency based on p95 latency estimates.",
        "Still vulnerable to SSRF if allowlists weak—defense in depth required.",
    ),
    entry(
        "adv-circuit-breaker-http",
        "advanced",
        "Circuit breaker HTTP toolpack",
        "Per-endpoint breaker states (closed/open/half-open) in memory + optional Redis.",
        "resilience",
        "typescript",
        "stdio",
        "Protect fragile internal services from retry storms initiated by LLM loops.",
        "Wrap fetch in breaker registry keyed by `serviceKey`. Expose `call` tool and `reset_breaker` admin-guarded. Half-open trial count configurable. Emit metrics counters for transitions.",
        ["cb_call", "cb_reset", "cb_status"],
        "Integrate with OpenTelemetry spans around attempts.",
        "Reset tool misuse can prolong outages—RBAC on reset.",
    ),
    entry(
        "adv-event-inbox",
        "advanced",
        "Inbox processor for durable events",
        "At-least-once consumer pattern with idempotent handlers keyed by event id.",
        "eventing",
        "python",
        "stdio",
        "Agents reacting to webhooks need dedupe and poison pill handling.",
        "Backed by Postgres table `inbox(event_id pk, payload, status)`. Tools: `enqueue_event` (internal), `process_next` transactional claiming, `quarantine_event`. Handler idempotency keys documented. Visibility timeout pattern.",
        ["process_next", "quarantine_event", "replay_event"],
        "Add outbox publisher sidecar pattern description in resources.",
        "Poison messages can block if not quarantined—monitor queue depth.",
    ),
    entry(
        "adv-dag-runner",
        "advanced",
        "YAML DAG workflow runner",
        "Execute acyclic steps with declared dependencies and typed outputs.",
        "automation",
        "typescript",
        "stdio",
        "Complex multi-tool agent routines become reproducible workflows checked into git.",
        "Parse YAML schema validating DAG. Topological sort. Each step maps to registered sub-tool name with input templating from prior outputs using JSONPath subset. Global timeout and per-step timeout. Persist run manifest to tmp with redaction.",
        ["run_workflow", "validate_workflow", "cancel_run"],
        "Add human approval step type emitting pending resource.",
        "Turing-complete templating forbidden—keep JSONPath limited.",
    ),
    entry(
        "adv-rag-connector-pattern",
        "advanced",
        "RAG ingestion connector pattern",
        "Chunk, hash, and enqueue documents for an external vector index.",
        "ai",
        "python",
        "stdio",
        "Enterprise RAG separates embedding from retrieval; MCP orchestrates ingestion side.",
        "Tools: `chunk_text` with semantic sliding window, `embed_and_upsert` calling configured HTTP embedding service with API key from env, `delete_by_source`. Store chunk table in Postgres with vector column optional. Strong content hash dedupe.",
        ["chunk_text", "embed_and_upsert", "delete_by_source"],
        "Add layout-aware PDF extractor behind sandbox worker—not in-process.",
        "Embedding PII into vectors is hard to erase—classification step required.",
    ),
    entry(
        "adv-sql-guardrails",
        "advanced",
        "SQL dialect guardrail analyzer",
        "Statically scan SQL for disallowed constructs before execution proxy.",
        "database",
        "typescript",
        "stdio",
        "When LLM-generated SQL must run, a second line of defense beyond parameterization helps.",
        "Use parser (e.g. node-sql-parser) to build AST; ban `DELETE`, `UPDATE`, `INSERT`, DDL, comments tricks, multiple statements, `into outfile`. Tool `analyze_sql` returns violations with line refs. Pair with `explain_sql` passthrough to read replica only.",
        ["analyze_sql", "format_sql_safe"],
        "Dialect modules plug-in via config.",
        "Parser evasion attempts evolve—combine with DB roles read-only.",
    ),
    entry(
        "adv-mcp-fanout-proxy",
        "advanced",
        "MCP child-server fan-out proxy",
        "Aggregate tools/resources from multiple downstream MCP processes.",
        "platform",
        "typescript",
        "stdio",
        "Composite agents want one connection while reusing specialized servers safely.",
        "Supervisor launches stdio children from allowlisted commands in config. Maps downstream tool names with `child::tool` prefix. Propagate cancellation. Health check cycles restart crashed children with backoff.",
        ["list_children", "call_child_tool", "child_health"],
        "Add streaming resource proxy for large artifacts.",
        "Child servers are still process boundaries—resource accounting needed.",
    ),
    entry(
        "adv-rbac-tool-visibility",
        "advanced",
        "RBAC-filtered tool catalog",
        "Expose different `list_tools` results based on OAuth scopes.",
        "security",
        "python",
        "stdio",
        "Enterprise admins want least-privilege tool exposure per principal.",
        "On session bind, map scopes→tool allowlist. Wrap list_tools handler to filter. `call_tool` verifies scope again. Structured `permission_denied` errors. Optional audit log of denied attempts rate-limited.",
        ["list_tools_scoped", "explain_permissions"],
        "Integrate with OPA policy bundle fetch periodically.",
        "Scope enumeration bugs could hide tools but leaks via timing—document.",
    ),
    entry(
        "adv-audit-stream",
        "advanced",
        "Audit log streaming tool",
        "Append-only JSONL audit events for sensitive tool calls.",
        "compliance",
        "typescript",
        "stdio",
        "Regulated industries require immutable-ish audit trails for AI actions.",
        "Tool `record_audit` writes to GCS object or local volume with hash chain (prev_hash, row). Reads disallowed via MCP; separate SIEM ingestion. Include actor, tenant, tool, arguments_digest, outcome.",
        ["record_audit", "verify_chain_tail"],
        "Ship KMS-signed chain head rotation design in README resource.",
        "Local volumes can be tampered—prefer remote immutable storage.",
    ),
    entry(
        "adv-pii-scan-json",
        "advanced",
        "Structured PII scanner",
        "Detect emails, phones, government IDs in nested JSON using rulesets.",
        "compliance",
        "python",
        "stdio",
        "Before exfil to external LLM, automated scanning flags records needing redaction.",
        "Walk JSON tree with depth/size caps. Pluggable detectors with confidence scores. Output paths + type + masked preview. Separate `apply_masks` tool returning transformed JSON.",
        ["scan_json_pii", "apply_masks"],
        "Add custom regex detectors via config file loaded at startup only.",
        "False negatives/positives—human review for high stakes.",
    ),
    entry(
        "adv-moderation-prehook",
        "advanced",
        "Content moderation pre-hook",
        "Call provider moderation API on user-supplied text arguments before main tool.",
        "safety",
        "typescript",
        "stdio",
        "Public-facing MCPs reduce abuse by scanning prompts destined for external APIs.",
        "Middleware layer wraps each tool: serialize args text, call moderation HTTP with zero retention flag if supported, block categories configurable. Adds latency budget with fail-closed or fail-open policy per deployment.",
        ["moderate_text", "wrapped_echo_demo"],
        "Add image moderation variant with size cap and hash dedupe.",
        "Policy misconfiguration can block legit traffic—monitor block rates.",
    ),
    entry(
        "adv-cosign-verify",
        "advanced",
        "Artifact signature verification",
        "Verify Sigstore/cosign signatures on container digests (design-level).",
        "supply-chain",
        "python",
        "stdio",
        "Deploy pipelines want AI-checked gates verifying signed images before promotion.",
        "Tool `verify_image` shells to `cosign verify` with public key ref from config OR uses Python sigstore libs if available. Captures JSON output. No network except Rekor/OIDC as configured.",
        ["verify_image", "parse_attestation"],
        "Add SBOM fetch linkage with `cosign download sbom`.",
        "Supply chain tools must be pinned versions; OIDC token handling sensitive.",
    ),
    entry(
        "adv-vault-lease-renewal",
        "advanced",
        "Vault token lease helper",
        "Renew leases and fetch dynamic DB creds with tight TTL (pattern).",
        "secrets",
        "typescript",
        "stdio",
        "Short-lived creds for DB tools reduce blast radius when agents are compromised.",
        "Uses Vault SDK with `VAULT_ADDR` and `VAULT_TOKEN` from env injected by platform—not user args. Tools: `renew_self`, `read_database_creds` role-based. Never return token to model—only username/password with 60s TTL and reminder comment.",
        ["renew_self", "read_database_creds"],
        "Add PKI cert issuance read-only listing (no private key export).",
        "Leaked wrapped tokens in logs catastrophic—scrub logs aggressively.",
    ),
    entry(
        "adv-oauth-device-flow",
        "advanced",
        "OAuth2 device flow helper",
        "Orchestrate device authorization grant for CLI MCP users.",
        "security",
        "python",
        "stdio",
        "When stdio MCP cannot open a browser, device flow obtains refresh tokens safely.",
        "Tools: `start_device_auth` returning `user_code` URL, `poll_token` until expiry. Persist state in local encrypted file with OS keychain optional design. Clear separation: no secrets printed to stdout beyond one-time user instructions.",
        ["start_device_auth", "poll_token", "revoke_token"],
        "Add PKCE pairing for public clients where required.",
        "User training on verifying device codes to prevent phishing.",
    ),
    entry(
        "adv-graphql-federated-query",
        "advanced",
        "Federated GraphQL gateway client",
        "Send queries to gateway with persisted query allowlist.",
        "integration",
        "typescript",
        "stdio",
        "Microservice architectures expose a supergraph; agents should not ship arbitrary GraphQL strings.",
        "Maintain map `queryName -> gql document`. Tool `run_persisted_query` with variables JSON only. Apollo router or similar endpoint from env. Complexity metrics logged.",
        ["run_persisted_query", "list_allowed_queries"],
        "Add `@defer` handling notes as resource doc.",
        "Allowlisting shifts maintenance burden—CI validation for new queries.",
    ),
    entry(
        "adv-ws-price-bridge",
        "advanced",
        "WebSocket market data bridge",
        "Stream normalized ticks to resources while tools snapshot latest.",
        "streaming",
        "python",
        "stdio",
        "Financial copilots need near-real-time numbers without polling REST.",
        "Background task subscribes to WS with reconnect+jitter. In-memory ring buffer. Tool `latest_quote` reads buffer; resource `market://ticks` exposes SSE-like stream if transport supports (note SSE limitations). Strict symbol allowlist.",
        ["latest_quote", "subscribe_symbols"],
        "Add circuit for stale data if feed silent >N seconds.",
        "Market data licensing—user responsibility.",
    ),
    entry(
        "adv-cdc-debezium-pattern",
        "advanced",
        "CDC offset bookmark tool",
        "Track Kafka/Debezium offsets for at-least-once agent processing.",
        "eventing",
        "typescript",
        "stdio",
        "Agents consuming change streams must resume safely after restarts.",
        "Tools: `commit_offset`, `get_offset` backed by compacted Kafka topic or DynamoDB. Include partition key strategy docs. Validate monotonicity.",
        ["commit_offset", "get_offset", "reset_offset"],
        "Add schema registry compatibility check hook.",
        "Wrong offset commits can skip or duplicate business events—monitor lag.",
    ),
    entry(
        "adv-idempotent-http-post",
        "advanced",
        "Idempotent POST relay",
        "Relay POSTs with `Idempotency-Key` header and server-side replay cache.",
        "integration",
        "python",
        "stdio",
        "LLM retries duplicate side effects; idempotency keys make POST safe.",
        "Redis cache stores response body hash keyed by idempotency key + route with TTL 24h. Tool `post_idempotent` requires key from caller or generates deterministic from canonical args hash (document tradeoffs). Returns cached response on replay.",
        ["post_idempotent"],
        "Add body canonicalization rules to avoid key fragmentation.",
        "Cache poisoning if key space shared across tenants—namespace keys.",
    ),
    entry(
        "adv-distributed-lock",
        "advanced",
        "Redis distributed lock",
        "Acquire/extend/release locks with fencing token pattern.",
        "distributed-systems",
        "typescript",
        "stdio",
        "Multi-worker agents coordinating migrations need locks beyond LLM politeness.",
        "Tool `acquire_lock` returns `{ token, leaseId }` using Redlock-ish algorithm simplified. `extend_lock`, `release_lock` verify token match. Fencing token increments stored in Redis for downstream DB writes optional doc.",
        ["acquire_lock", "extend_lock", "release_lock"],
        "Add `try_lock` non-blocking variant.",
        "Clock skew breaks locks—document NTP requirements.",
    ),
    entry(
        "adv-saga-compensations",
        "advanced",
        "Saga compensation planner",
        "Given ordered steps with undo URIs, execute forwards with rollback on failure (HTTP).",
        "distributed-systems",
        "python",
        "stdio",
        "Orchestrating purchases across services requires explicit compensations.",
        "YAML saga definition lists `forward` and `compensate` URLs per step. Engine executes forwards; on error unwinds compensations in reverse order with payload echo from forward response ids. Timeouts per leg.",
        ["run_saga", "validate_saga"],
        "Add partial completion human task emission resource.",
        "Compensations themselves can fail—needs out-of-band reconciliation.",
    ),
    entry(
        "adv-cost-estimator",
        "advanced",
        "Token and API cost estimator",
        "Estimate USD cost from token usage histogram + provider price table version.",
        "ai-ops",
        "typescript",
        "stdio",
        "FinOps for agent runs: attribute estimated dollars to tenants and tools.",
        "Static price table versioned dated. Tool `estimate_cost` inputs counts per model id; outputs subtotal + disclaimer. Separate `attribute_by_tool` taking run manifest JSON.",
        ["estimate_cost", "attribute_by_tool"],
        "Pull live pricing optional via cached HTTP daily.",
        "Estimates != invoices; tax and discounts ignored.",
    ),
    entry(
        "adv-deploy-gate",
        "advanced",
        "Blue/green deploy readiness gate",
        "Aggregate health checks + error budget burn before go/no-go.",
        "delivery",
        "python",
        "stdio",
        "Release managers want an MCP tool that answers 'safe to promote' with evidence.",
        "Tool `evaluate_release` calls configured HTTP health endpoints in parallel, reads Prometheus error budget query, applies policy thresholds from YAML. Returns structured verdict and reasons array.",
        ["evaluate_release", "dry_run_policies"],
        "Add canary metrics window comparison optional.",
        "False negatives can block revenue—tune policies carefully.",
    ),
    entry(
        "adv-soc2-checklist-runner",
        "advanced",
        "SOC2 evidence checklist runner",
        "Run scripted checks (TLS versions, bucket logging flags) via read-only cloud APIs.",
        "compliance",
        "typescript",
        "stdio",
        "GRC assistants collect repeatable evidence for auditors with timestamps.",
        "Pluggable checks as modules exporting `run(ctx): Finding[]`. Tools: `run_suite`, `export_findings_json`. Cloud creds via ambient AWS/GCP metadata in worker—not end user laptop for production.",
        ["run_suite", "export_findings_json"],
        "Map findings to control IDs as configurable table.",
        "Mis-scoped IAM can read sensitive infra—read-only least privilege.",
    ),
    entry(
        "adv-envelope-encryption",
        "advanced",
        "Envelope encryption helper",
        "Generate data key, encrypt DEK with KMS, return ciphertext bundle JSON.",
        "security",
        "python",
        "stdio",
        "Agents storing customer data must avoid shipping plaintext keys in prompts.",
        "Tool `encrypt_payload` calls KMS GenerateDataKey, encrypts payload with AES-GCM locally, returns `{ ciphertext, iv, wrappedDek, kmsKeyId }`. `decrypt_payload` reverses with KMS Decrypt. All crypto in vetted libs.",
        ["encrypt_payload", "decrypt_payload", "rotate_wrapped_dek"],
        "Add context AAD binding tenant id.",
        "Cryptographic misuse easy—require security review before prod.",
    ),
    entry(
        "adv-llm-router-latency",
        "advanced",
        "Multi-model LLM router",
        "Route completions to model A/B based on SLA, cost, and safety tier.",
        "ai-ops",
        "typescript",
        "stdio",
        "High-volume agents optimize price/performance dynamically while respecting safety.",
        "Maintains rolling p95 latency per model from recent calls stored in Redis. Tool `route_completion` selects model per policy JSON: prefer cheapest under latency SLO else escalate. Does not hold provider keys in repo—calls internal gateway only.",
        ["route_completion", "report_slo"],
        "Add circuit for provider outage detection.",
        "Routing bias can starve premium model budget—watchdog caps.",
    ),
    entry(
        "adv-zero-trust-mtls",
        "advanced",
        "mTLS service mesh caller",
        "Call internal REST services presenting SPIFFE-derived client certs.",
        "platform",
        "python",
        "stdio",
        "Zero-trust meshes require cert rotation and SAN verification—not typical bearer flows.",
        "Load certs from SDS socket or filesystem paths from env. Tool `mesh_request` validates server cert chain against mesh trust bundle. Logs SPIFFE ID only.",
        ["mesh_request", "rotate_sds_hint"],
        "Add workload identity attestation resource stub.",
        "Cert misconfiguration causes subtle partial TLS—strong tests needed.",
    ),
    entry(
        "adv-policy-as-code-opa",
        "advanced",
        "OPA policy evaluation sidecar",
        "Evaluate Rego bundles for allow/deny on tool arguments pre-execution.",
        "compliance",
        "typescript",
        "stdio",
        "Organizations centralize authorization in OPA; MCP should query policies before side effects.",
        "Tool `policy_check` sends `{ input: { tool, args_digest, tenant } }` to OPA HTTP API. Bundle version pinned. Deny wins default. Cache decisions briefly keyed by hash.",
        ["policy_check", "explain_deny"],
        "Add bundle hot-reload watch with backoff.",
        "Incomplete Rego can default allow—fail-closed config flag required.",
    ),
    entry(
        "adv-observability-correlation",
        "advanced",
        "Distributed tracing propagation",
        "Inject/extract W3C tracecontext headers on outbound HTTP tool calls.",
        "observability",
        "python",
        "stdio",
        "Debugging agent chains across services needs shared trace ids.",
        "Maintain current span context in contextvars. Tool `call_traced_http` wraps httpx injecting headers from active span. Export spans to OTLP endpoint from env optional.",
        ["call_traced_http", "attach_correlation_id"],
        "Add baggage propagation limits to avoid header bloat.",
        "PII in baggage forbidden—validators required.",
    ),
    entry(
        "adv-quota-budget-server",
        "advanced",
        "Tenant budget enforcer",
        "Enforce per-day token and tool-call budgets persisted in Postgres.",
        "platform",
        "typescript",
        "stdio",
        "SaaS MCP hosts must cap runaway agent spend per customer.",
        "Middleware decrements budget atomically with row locks. Tools return `budget_exceeded` error including reset time UTC. Admin tool `adjust_budget` behind separate auth scope.",
        ["check_and_consume", "budget_status", "adjust_budget"],
        "Add soft warnings at 80% consumption in metadata channel.",
        "Clock skew affects reset windows—use DB timestamptz.",
    ),
    entry(
        "adv-secure-code-exec-isolation",
        "advanced",
        "Isolated code execution broker MCP",
        "Queue snippets to sandbox workers; never execute in API process (pattern).",
        "security",
        "python",
        "stdio",
        "Some advanced templates describe user-code execution—this pattern routes to gVisor/Firecracker sandboxes via queue.",
        "Tools: `submit_job` returns job id; `poll_result` returns stdout/stderr capped; `cancel_job`. Signed payloads. Resource CPU/mem/time limits enforced worker-side only.",
        ["submit_job", "poll_result", "cancel_job"],
        "Add language allowlist per tenant.",
        "Wrong isolation equals RCE—treat as highest risk surface.",
    ),
]

ALL = BASIC + INTERMEDIATE + ADVANCED


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {"version": 1, "blueprints": ALL}
    JSON_OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(ALL)} blueprints to {JSON_OUT}")
    # TypeScript module exporting const + type
    lines = [
        "// AUTO-GENERATED by scripts/build_mcp_template_catalog.py — do not hand-edit.",
        "export type TemplateTier = \"basic\" | \"intermediate\" | \"advanced\";",
        "",
        "export type McpTemplateBlueprint = {",
        "  id: string;",
        "  tier: TemplateTier;",
        "  name: string;",
        "  tagline: string;",
        "  category: string;",
        "  primaryRuntime: \"typescript\" | \"python\";",
        "  transport: \"stdio\" | \"sse\";",
        "  overview: string;",
        "  design: string;",
        "  suggestedTools: readonly string[];",
        "  extensionIdeas: string;",
        "  risks: string;",
        "};",
        "",
        "export const MCP_TEMPLATE_BLUEPRINTS: readonly McpTemplateBlueprint[] = ",
        json.dumps(ALL, indent=2, ensure_ascii=False) + " as const;",
        "",
        "export const MCP_TEMPLATE_COUNTS: Record<TemplateTier, number> = {",
        "  basic: "
        + str(sum(1 for x in ALL if x["tier"] == "basic"))
        + ",",
        "  intermediate: "
        + str(sum(1 for x in ALL if x["tier"] == "intermediate"))
        + ",",
        "  advanced: "
        + str(sum(1 for x in ALL if x["tier"] == "advanced"))
        + ",",
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(ALL)} templates to {OUT} and JSON catalog")


if __name__ == "__main__":
    main()
